//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I3SwebAPIv2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I3SwebAPIv2.Resources.WebApiResources", typeof(WebApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been verified. Please login to continue..
        /// </summary>
        internal static string AccountAlreadyVerify {
            get {
                return ResourceManager.GetString("AccountAlreadyVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully. You will be logged out automatically. .
        /// </summary>
        internal static string AccountDeleteSuccess {
            get {
                return ResourceManager.GetString("AccountDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account could not be found..
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been verified. Please change your card PIN..
        /// </summary>
        internal static string AccountVerifySuccess {
            get {
                return ResourceManager.GetString("AccountVerifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been verified. Please login to continue. .
        /// </summary>
        internal static string AccountVerifySuccessMerchant {
            get {
                return ResourceManager.GetString("AccountVerifySuccessMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment successfully uploaded..
        /// </summary>
        internal static string AttUploadSuccess {
            get {
                return ResourceManager.GetString("AttUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your documents are awaiting verification. Please check your email for status update..
        /// </summary>
        internal static string AwaitingVerificationMpay {
            get {
                return ResourceManager.GetString("AwaitingVerificationMpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 - Bad Request.
        /// </summary>
        internal static string BadRequestText {
            get {
                return ResourceManager.GetString("BadRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card daily limit successfully updated..
        /// </summary>
        internal static string CardLimitUpdateSuccess {
            get {
                return ResourceManager.GetString("CardLimitUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin number changed successfully. Please login using your MyKad / Passport number as Username to proceed..
        /// </summary>
        internal static string CardPinChangeSuccessText {
            get {
                return ResourceManager.GetString("CardPinChangeSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card has successfully been replaced..
        /// </summary>
        internal static string CardReplaceSuccess {
            get {
                return ResourceManager.GetString("CardReplaceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card status already blacklisted..
        /// </summary>
        internal static string CardStatusAlreadyBlacklist {
            get {
                return ResourceManager.GetString("CardStatusAlreadyBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card status not active..
        /// </summary>
        internal static string CardStatusNotActive {
            get {
                return ResourceManager.GetString("CardStatusNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card status successfully updated..
        /// </summary>
        internal static string CardStatusUpdateSuccess {
            get {
                return ResourceManager.GetString("CardStatusUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already joined this channel..
        /// </summary>
        internal static string ChannelAlreadyJoin {
            get {
                return ResourceManager.GetString("ChannelAlreadyJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel successfully joined..
        /// </summary>
        internal static string ChannelJoinSuccess {
            get {
                return ResourceManager.GetString("ChannelJoinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already left this channel..
        /// </summary>
        internal static string ChannelLeaveSuccess {
            get {
                return ResourceManager.GetString("ChannelLeaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class attendance report could not be found..
        /// </summary>
        internal static string ClassAttendanceReportNotFound {
            get {
                return ResourceManager.GetString("ClassAttendanceReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class attendance report successfully exported..
        /// </summary>
        internal static string ClassAttendanceReportSuccess {
            get {
                return ResourceManager.GetString("ClassAttendanceReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Daily Order Report.
        /// </summary>
        internal static string ClassDailyOrderReportTitle {
            get {
                return ResourceManager.GetString("ClassDailyOrderReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class daily order report could not be found..
        /// </summary>
        internal static string ClassOrderReportNotFound {
            get {
                return ResourceManager.GetString("ClassOrderReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class daily order report successfully exported..
        /// </summary>
        internal static string ClassOrderReportSuccess {
            get {
                return ResourceManager.GetString("ClassOrderReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class relationship successfully created..
        /// </summary>
        internal static string ClassRelationshipCreateSuccess {
            get {
                return ResourceManager.GetString("ClassRelationshipCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class relationship already exists..
        /// </summary>
        internal static string ClassRelationshipExist {
            get {
                return ResourceManager.GetString("ClassRelationshipExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class relationship could not be found..
        /// </summary>
        internal static string ClassRelationshipNotFound {
            get {
                return ResourceManager.GetString("ClassRelationshipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class relationship successfully removed..
        /// </summary>
        internal static string ClassRelationshipRemoveSuccess {
            get {
                return ResourceManager.GetString("ClassRelationshipRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student already enrolled into the class..
        /// </summary>
        internal static string ClassStudentExist {
            get {
                return ResourceManager.GetString("ClassStudentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class teacher already exist. full_name is the current class teacher..
        /// </summary>
        internal static string ClassTeacherExist {
            get {
                return ResourceManager.GetString("ClassTeacherExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club attendance already exists..
        /// </summary>
        internal static string ClubAttAlreadyExist {
            get {
                return ResourceManager.GetString("ClubAttAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club attendance created successfully..
        /// </summary>
        internal static string ClubAttCreatedSuccess {
            get {
                return ResourceManager.GetString("ClubAttCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club successfully handed over..
        /// </summary>
        internal static string ClubHandoverSuccess {
            get {
                return ResourceManager.GetString("ClubHandoverSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club member already exists..
        /// </summary>
        internal static string ClubMemberExist {
            get {
                return ResourceManager.GetString("ClubMemberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club member could not be found..
        /// </summary>
        internal static string ClubMemberNotFound {
            get {
                return ResourceManager.GetString("ClubMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club member successfully removed..
        /// </summary>
        internal static string ClubMemberRemoveSuccess {
            get {
                return ResourceManager.GetString("ClubMemberRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club relationship successfully created..
        /// </summary>
        internal static string ClubRelationshipCreateSuccess {
            get {
                return ResourceManager.GetString("ClubRelationshipCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club relationship already exists..
        /// </summary>
        internal static string ClubRelationshipExist {
            get {
                return ResourceManager.GetString("ClubRelationshipExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club relationship could not be found..
        /// </summary>
        internal static string ClubRelationshipNotFound {
            get {
                return ResourceManager.GetString("ClubRelationshipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club relationship successfully removed..
        /// </summary>
        internal static string ClubRelationshipRemoveSuccess {
            get {
                return ResourceManager.GetString("ClubRelationshipRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer document rejected, please resubmit through i-3s mobile app to proceed..
        /// </summary>
        internal static string CustomerDocumentRejected {
            get {
                return ResourceManager.GetString("CustomerDocumentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer rejected, please contact call center for further detail..
        /// </summary>
        internal static string CustomerRejected {
            get {
                return ResourceManager.GetString("CustomerRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document successfully submitted.
        /// </summary>
        internal static string DocumentResubmitSuccess {
            get {
                return ResourceManager.GetString("DocumentResubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format invalid..
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured, please try again..
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excused.
        /// </summary>
        internal static string Excused {
            get {
                return ResourceManager.GetString("Excused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email..
        /// </summary>
        internal static string FailToSendEmail {
            get {
                return ResourceManager.GetString("FailToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403 - Forbidden.
        /// </summary>
        internal static string ForbiddenText {
            get {
                return ResourceManager.GetString("ForbiddenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity number is invalid..
        /// </summary>
        internal static string IdentityNoInvalid {
            get {
                return ResourceManager.GetString("IdentityNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity number already registered..
        /// </summary>
        internal static string IdentityNumberAlreadyExist {
            get {
                return ResourceManager.GetString("IdentityNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image successfully uploaded..
        /// </summary>
        internal static string ImageUploadSuccess {
            get {
                return ResourceManager.GetString("ImageUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of a lost or stolen card, please report a lost/stolen card first before you request for a card replacement. This will minimize the chances of losing your eWallet balance..
        /// </summary>
        internal static string InCaseLostStolenCard {
            get {
                return ResourceManager.GetString("InCaseLostStolenCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Username is incorrect or you are not yet registered..
        /// </summary>
        internal static string IncorrectUsername {
            get {
                return ResourceManager.GetString("IncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient wallet balance..
        /// </summary>
        internal static string InsufficientWalletBalance {
            get {
                return ResourceManager.GetString("InsufficientWalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 - Internal Server Error.
        /// </summary>
        internal static string InternalServerErrorText {
            get {
                return ResourceManager.GetString("InternalServerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount..
        /// </summary>
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recipient wallet number..
        /// </summary>
        internal static string InvalidRecipientWalletNo {
            get {
                return ResourceManager.GetString("InvalidRecipientWalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-Wallet number..
        /// </summary>
        internal static string InvalidWalletNo {
            get {
                return ResourceManager.GetString("InvalidWalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        internal static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum OTP tryout limit exceeded..
        /// </summary>
        internal static string MaxOTPTryout {
            get {
                return ResourceManager.GetString("MaxOTPTryout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is invalid..
        /// </summary>
        internal static string MobileNoInvalid {
            get {
                return ResourceManager.GetString("MobileNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Attendance Report.
        /// </summary>
        internal static string MonthlyAttendanceReport {
            get {
                return ResourceManager.GetString("MonthlyAttendanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New card not found! Please enter a valid new card number..
        /// </summary>
        internal static string NewCardNotFound {
            get {
                return ResourceManager.GetString("NewCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chairman must be a member of this club..
        /// </summary>
        internal static string NewChairmanMustBeMember {
            get {
                return ResourceManager.GetString("NewChairmanMustBeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student have been successfully enrolled into the class..
        /// </summary>
        internal static string NewClassStudentCreateSuccess {
            get {
                return ResourceManager.GetString("NewClassStudentCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New club member successfully created..
        /// </summary>
        internal static string NewClubMemberCreateSuccess {
            get {
                return ResourceManager.GetString("NewClubMemberCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New bulletin successfully created..
        /// </summary>
        internal static string NewPostCreateSuccess {
            get {
                return ResourceManager.GetString("NewPostCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New registration.
        /// </summary>
        internal static string NewRegistrationText {
            get {
                return ResourceManager.GetString("NewRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        internal static string NoRecordFoundText {
            get {
                return ResourceManager.GetString("NoRecordFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status.
        /// </summary>
        internal static string NoStatus {
            get {
                return ResourceManager.GetString("NoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - Not Found.
        /// </summary>
        internal static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order history has been removed..
        /// </summary>
        internal static string OrderHistoryRemoved {
            get {
                return ResourceManager.GetString("OrderHistoryRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order history has been placed in the cart..
        /// </summary>
        internal static string OrderHistoryUpdate {
            get {
                return ResourceManager.GetString("OrderHistoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same-day online orders must be placed before 7:00 AM. Please remove your order for today to continue payment..
        /// </summary>
        internal static string OrderMustBePlacedBfor7 {
            get {
                return ResourceManager.GetString("OrderMustBePlacedBfor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status successfully updated..
        /// </summary>
        internal static string OrderStatusUpdateSuccess {
            get {
                return ResourceManager.GetString("OrderStatusUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Timing.
        /// </summary>
        internal static string OrderTiming {
            get {
                return ResourceManager.GetString("OrderTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been sent to .
        /// </summary>
        internal static string OTPHasBeenSent {
            get {
                return ResourceManager.GetString("OTPHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has expired..
        /// </summary>
        internal static string OTPHasExpired {
            get {
                return ResourceManager.GetString("OTPHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Identity Number has been registered as a parent..
        /// </summary>
        internal static string ParentIDAlreadyExist {
            get {
                return ResourceManager.GetString("ParentIDAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent-student relationship successfully created..
        /// </summary>
        internal static string ParentStudentRelationshipCreateSuccess {
            get {
                return ResourceManager.GetString("ParentStudentRelationshipCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent-student relationship already exists..
        /// </summary>
        internal static string ParentStudentRelationshipExist {
            get {
                return ResourceManager.GetString("ParentStudentRelationshipExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending customer activation.
        /// </summary>
        internal static string PendingActivation {
            get {
                return ResourceManager.GetString("PendingActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo successfully removed..
        /// </summary>
        internal static string PhotoSuccessRemove {
            get {
                return ResourceManager.GetString("PhotoSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for reset password link..
        /// </summary>
        internal static string PleaseCheckYourEmail {
            get {
                return ResourceManager.GetString("PleaseCheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create your new password..
        /// </summary>
        internal static string PleaseCreateNewPassword {
            get {
                return ResourceManager.GetString("PleaseCreateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string PleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("PleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload your MyKad / Passport image and your selfie image for verification process..
        /// </summary>
        internal static string PleaseUploadYourImage {
            get {
                return ResourceManager.GetString("PleaseUploadYourImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please clear the balance in student wallet..
        /// </summary>
        internal static string PlsClearWalletBalance {
            get {
                return ResourceManager.GetString("PlsClearWalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create your new password..
        /// </summary>
        internal static string PlsCreateNewPswd {
            get {
                return ResourceManager.GetString("PlsCreateNewPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string PlsEnterPswd {
            get {
                return ResourceManager.GetString("PlsEnterPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletin successfully removed..
        /// </summary>
        internal static string PostSuccessRemove {
            get {
                return ResourceManager.GetString("PostSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletin successfully updated..
        /// </summary>
        internal static string PostUpdateSuccess {
            get {
                return ResourceManager.GetString("PostUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By.
        /// </summary>
        internal static string PreparedBy {
            get {
                return ResourceManager.GetString("PreparedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed Date/Time.
        /// </summary>
        internal static string PrintedDateTime {
            get {
                return ResourceManager.GetString("PrintedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category successfully created..
        /// </summary>
        internal static string ProductCategoryCreateSuccess {
            get {
                return ResourceManager.GetString("ProductCategoryCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category successfully deleted..
        /// </summary>
        internal static string ProductCategoryDeleteSuccess {
            get {
                return ResourceManager.GetString("ProductCategoryDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category already exists..
        /// </summary>
        internal static string ProductCategoryExist {
            get {
                return ResourceManager.GetString("ProductCategoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product category successfully updated..
        /// </summary>
        internal static string ProductCategoryUpdateSuccess {
            get {
                return ResourceManager.GetString("ProductCategoryUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Daily Order Report.
        /// </summary>
        internal static string ProductDailyOrderReport {
            get {
                return ResourceManager.GetString("ProductDailyOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product detail successfully created..
        /// </summary>
        internal static string ProductDetailCreateSuccess {
            get {
                return ResourceManager.GetString("ProductDetailCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product detail successfully deleted..
        /// </summary>
        internal static string ProductDetailDeleteSuccess {
            get {
                return ResourceManager.GetString("ProductDetailDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product detail already exists..
        /// </summary>
        internal static string ProductDetailExist {
            get {
                return ResourceManager.GetString("ProductDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product detail successfully updated..
        /// </summary>
        internal static string ProductDetailUpdateSuccess {
            get {
                return ResourceManager.GetString("ProductDetailUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product daily order report could not be found..
        /// </summary>
        internal static string ProductOrderReportNotFound {
            get {
                return ResourceManager.GetString("ProductOrderReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product daily order report successfully exported..
        /// </summary>
        internal static string ProductOrderReportSuccess {
            get {
                return ResourceManager.GetString("ProductOrderReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated..
        /// </summary>
        internal static string ProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("ProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match..
        /// </summary>
        internal static string PswdNotMatch {
            get {
                return ResourceManager.GetString("PswdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully updated..
        /// </summary>
        internal static string PswdUpdateSuccess {
            get {
                return ResourceManager.GetString("PswdUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuantiti.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received your order..
        /// </summary>
        internal static string ReceiveOrder {
            get {
                return ResourceManager.GetString("ReceiveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account has been registered as a staff before. Would you like to register as a parent / guardian as well?.
        /// </summary>
        internal static string RegisterDoubleRole {
            get {
                return ResourceManager.GetString("RegisterDoubleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account has been registered. Please login using your MyKad / Passport number as Username to proceed..
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 408 - Request Timeout.
        /// </summary>
        internal static string RequestTimeoutText {
            get {
                return ResourceManager.GetString("RequestTimeoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club name already exists..
        /// </summary>
        internal static string SchoolClubExist {
            get {
                return ResourceManager.GetString("SchoolClubExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New club successfully created..
        /// </summary>
        internal static string SchoolClubSaveSuccess {
            get {
                return ResourceManager.GetString("SchoolClubSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        internal static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Pick-up.
        /// </summary>
        internal static string SelfPickup {
            get {
                return ResourceManager.GetString("SelfPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Method.
        /// </summary>
        internal static string ServiceMethod {
            get {
                return ResourceManager.GetString("ServiceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is temporarily unavailable due to maintenance. Please try again later..
        /// </summary>
        internal static string ServiceTemporaryDown {
            get {
                return ResourceManager.GetString("ServiceTemporaryDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503 - Service Unavailable.
        /// </summary>
        internal static string ServiceUnavailableText {
            get {
                return ResourceManager.GetString("ServiceUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Code.
        /// </summary>
        internal static string ShiftCode {
            get {
                return ResourceManager.GetString("ShiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your account is not active..
        /// </summary>
        internal static string SorryAccNotActive {
            get {
                return ResourceManager.GetString("SorryAccNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your account is not active..
        /// </summary>
        internal static string SorryAccountInactive {
            get {
                return ResourceManager.GetString("SorryAccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff attendance report could not be found..
        /// </summary>
        internal static string StaffAttendanceReportNotFound {
            get {
                return ResourceManager.GetString("StaffAttendanceReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff attendance report successfully exported..
        /// </summary>
        internal static string StaffAttendanceReportSuccess {
            get {
                return ResourceManager.GetString("StaffAttendanceReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff attendance could not be found..
        /// </summary>
        internal static string StaffAttNotFound {
            get {
                return ResourceManager.GetString("StaffAttNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff attendance successfully updated..
        /// </summary>
        internal static string StaffAttUpdateSuccess {
            get {
                return ResourceManager.GetString("StaffAttUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Daily Order Report.
        /// </summary>
        internal static string StaffDailyOrderReportTitle {
            get {
                return ResourceManager.GetString("StaffDailyOrderReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        internal static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff could not be found..
        /// </summary>
        internal static string StaffNotFound {
            get {
                return ResourceManager.GetString("StaffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff daily order report could not be found..
        /// </summary>
        internal static string StaffOrderReportNotFound {
            get {
                return ResourceManager.GetString("StaffOrderReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff daily order report successfully exported..
        /// </summary>
        internal static string StaffOrderReportSuccess {
            get {
                return ResourceManager.GetString("StaffOrderReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff successfully removed..
        /// </summary>
        internal static string StaffRemoveSuccess {
            get {
                return ResourceManager.GetString("StaffRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff shift already exists..
        /// </summary>
        internal static string StaffShiftExist {
            get {
                return ResourceManager.GetString("StaffShiftExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff shift successfully updated..
        /// </summary>
        internal static string StaffShiftUpdateSuccess {
            get {
                return ResourceManager.GetString("StaffShiftUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status successfully updated..
        /// </summary>
        internal static string StatusUpdateSuccess {
            get {
                return ResourceManager.GetString("StatusUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student account successfully updated..
        /// </summary>
        internal static string StudentAccUpdateSuccess {
            get {
                return ResourceManager.GetString("StudentAccUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student attendance could not be found..
        /// </summary>
        internal static string StudentAttNotFound {
            get {
                return ResourceManager.GetString("StudentAttNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student attendance successfully updated..
        /// </summary>
        internal static string StudentAttUpdateSuccess {
            get {
                return ResourceManager.GetString("StudentAttUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student class already exists..
        /// </summary>
        internal static string StudentClassExist {
            get {
                return ResourceManager.GetString("StudentClassExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student class successfully updated..
        /// </summary>
        internal static string StudentClassUpdateSuccess {
            get {
                return ResourceManager.GetString("StudentClassUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student class could not be found..
        /// </summary>
        internal static string StudentClsNotFound {
            get {
                return ResourceManager.GetString("StudentClsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student class successfully removed..
        /// </summary>
        internal static string StudentClsRemoveSuccess {
            get {
                return ResourceManager.GetString("StudentClsRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Daily Order Report.
        /// </summary>
        internal static string StudentDailyOrderReport {
            get {
                return ResourceManager.GetString("StudentDailyOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student daily order report could not be found..
        /// </summary>
        internal static string StudentOrderReportNotFound {
            get {
                return ResourceManager.GetString("StudentOrderReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student daily order report successfully exported..
        /// </summary>
        internal static string StudentOrderReportSuccess {
            get {
                return ResourceManager.GetString("StudentOrderReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student relationship could not be found..
        /// </summary>
        internal static string StudentRelationshipNotFound {
            get {
                return ResourceManager.GetString("StudentRelationshipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student relationship successfully removed..
        /// </summary>
        internal static string StudentRelationshipRemoveSuccess {
            get {
                return ResourceManager.GetString("StudentRelationshipRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is much appreciated..
        /// </summary>
        internal static string ThankYouFeedback {
            get {
                return ResourceManager.GetString("ThankYouFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401 - Unauthorized.
        /// </summary>
        internal static string UnauthorizedText {
            get {
                return ResourceManager.GetString("UnauthorizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsufficient e-Wallet balance..
        /// </summary>
        internal static string UnsufficientWalletBalance {
            get {
                return ResourceManager.GetString("UnsufficientWalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is incorrect/not registered..
        /// </summary>
        internal static string UsernameIncorrect {
            get {
                return ResourceManager.GetString("UsernameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong OTP..
        /// </summary>
        internal static string WrongOTP {
            get {
                return ResourceManager.GetString("WrongOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been received..
        /// </summary>
        internal static string YourOrderHasBeenReceived {
            get {
                return ResourceManager.GetString("YourOrderHasBeenReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit top-up is unsuccessful..
        /// </summary>
        internal static string YourTopupFail {
            get {
                return ResourceManager.GetString("YourTopupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit top-up is successful..
        /// </summary>
        internal static string YourTopupSuccess {
            get {
                return ResourceManager.GetString("YourTopupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit transfer is unsuccessful..
        /// </summary>
        internal static string YourTransferFail {
            get {
                return ResourceManager.GetString("YourTransferFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit has been transferred..
        /// </summary>
        internal static string YourTransferSuccess {
            get {
                return ResourceManager.GetString("YourTransferSuccess", resourceCulture);
            }
        }
    }
}
